name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - latest
          - 0.32.1

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install missing dependencies
        if: matrix.os == 'macos-latest'
        run: brew install coreutils

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: vector --help
          version: ${{ matrix.version }}
